// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tournament.Infrastructure.Persistence;

#nullable disable

namespace Tournament.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TournamentDbContext))]
    partial class TournamentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tournament.Domain.Tournaments.DeletedUserProjection", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("DeletedUserProjections", (string)null);
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.Discipline", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int[]>("AllowedTeamSizes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Code");

                    b.HasIndex("IsActive");

                    b.ToTable("Disciplines", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "CS2",
                            AllowedTeamSizes = new[] { 1, 2, 5 },
                            IsActive = true,
                            Name = "CS2"
                        },
                        new
                        {
                            Code = "PUBG",
                            AllowedTeamSizes = new[] { 1, 2, 5 },
                            IsActive = true,
                            Name = "PUBG"
                        },
                        new
                        {
                            Code = "Valorant",
                            AllowedTeamSizes = new[] { 1, 2, 5 },
                            IsActive = true,
                            Name = "Valorant"
                        },
                        new
                        {
                            Code = "Standoff2",
                            AllowedTeamSizes = new[] { 1, 2, 5 },
                            IsActive = true,
                            Name = "Standoff2"
                        });
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.DoubleEliminationStanding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEliminated")
                        .HasColumnType("boolean");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "TeamId")
                        .IsUnique();

                    b.ToTable("DoubleEliminationStandings", (string)null);
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsTechnicalDefeat")
                        .HasColumnType("boolean");

                    b.Property<int?>("LoserScore")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LoserTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("TeamAId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamBId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WinnerScore")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.HasIndex("Status");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.PlayerRatingProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisciplineCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Elo")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineCode");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId", "DisciplineCode")
                        .IsUnique();

                    b.ToTable("PlayerRatingProjections", (string)null);
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BracketType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Number", "BracketType");

                    b.ToTable("Rounds", (string)null);
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.SwissStanding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double?>("BuchholzScore")
                        .HasColumnType("double precision");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("OpponentsJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "TeamId")
                        .IsUnique();

                    b.ToTable("SwissStandings", (string)null);
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("AverageElo")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CaptainPlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("TournamentId", "Name")
                        .IsUnique();

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Elo")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId", "PlayerId")
                        .IsUnique();

                    b.ToTable("TeamMembers", (string)null);
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentRoundNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("DisciplineCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[0]);

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("SwissRounds")
                        .HasColumnType("integer");

                    b.Property<int>("TeamSize")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineCode");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedTitle")
                        .IsUnique();

                    b.HasIndex("OrganizerId");

                    b.HasIndex("Status");

                    b.ToTable("Tournaments", (string)null);
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.TournamentParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LeftAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerNickname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TournamentId", "PlayerId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = TRUE");

                    b.ToTable("TournamentParticipants", (string)null);
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.UserProjection", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnName("created_at_utc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnName("deleted_at_utc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnName("role")
                        .HasColumnType("character varying(32)");

                    b.HasKey("UserId");

                    b.ToTable("user_projections", (string)null);
                });

            modelBuilder.Entity("TournamentPlatform.Messaging.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId", "ConsumerName");

                    b.ToTable("InboxMessages", (string)null);
                });

            modelBuilder.Entity("TournamentPlatform.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("EventType");

                    b.HasIndex("ProcessedAtUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.DoubleEliminationStanding", b =>
                {
                    b.HasOne("Tournament.Domain.Tournaments.Tournament", null)
                        .WithMany("DoubleEliminationStandings")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.Match", b =>
                {
                    b.HasOne("Tournament.Domain.Tournaments.Round", null)
                        .WithMany("Matches")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tournament.Domain.Tournaments.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tournament.Domain.Tournaments.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.Round", b =>
                {
                    b.HasOne("Tournament.Domain.Tournaments.Tournament", null)
                        .WithMany("Rounds")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.SwissStanding", b =>
                {
                    b.HasOne("Tournament.Domain.Tournaments.Tournament", null)
                        .WithMany("SwissStandings")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.Team", b =>
                {
                    b.HasOne("Tournament.Domain.Tournaments.Tournament", null)
                        .WithMany("Teams")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.TeamMember", b =>
                {
                    b.HasOne("Tournament.Domain.Tournaments.Team", null)
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.TournamentParticipant", b =>
                {
                    b.HasOne("Tournament.Domain.Tournaments.Tournament", null)
                        .WithMany("Participants")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.Round", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Tournament.Domain.Tournaments.Tournament", b =>
                {
                    b.Navigation("DoubleEliminationStandings");

                    b.Navigation("Participants");

                    b.Navigation("Rounds");

                    b.Navigation("SwissStandings");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
